### ISSUE TITLE
Prepare document keeps popping up the popup

### ISSUE THREAD

**Issue by kasbah** [badgeek/svg2shenzhen#1]
When I press "prepare document" and then click apply the popup re-appears. I have to click cancel to stop it.

**Comment by badgeek** [comment]
hi kaspar, did you get export function working?

**Comment by 5shekel** [comment]
might be connected, 
python2 was missing lib2xml 

but it did produce a clear error message
https://i.imgur.com/23z0S1a.png

**Comment by badgeek** [comment]
just hit close after "prepare document"

**Comment by kasbah** [comment]
So this is how it's supposed to be? Why not close it automatically after preparation completes? Seems confusing to do it this way. 

> did you get export function working?

Yes, I did manage to get the export working in the latest version. This is going to be awesome when I have more time to play with it!

**Comment by badgeek** [comment]
yes you have to hit close, i tried to find why this behaviour is happening but have no clue at all.. been loking other extension as well...

**Comment by kasbah** [comment]
I feel like it is a bug in that case and should remain open until a solution is found. I'll have a go at solving it (when I find time).

**Comment by badgeek** [comment]
kool, thx

**Comment by kasbah** [comment]
I had a look over the inkscape docs I could find but haven't found a way to automatically close it either. :frowning_face:
