### ISSUE TITLE
Export error

### ISSUE THREAD

**Issue by GuillermoTell** [badgeek/svg2shenzhen#100]
Hi, no idea about what's going on here. No Edge.Cuts exported. It doesn't finish exporting the module and gives this error:

Traceback (most recent call last):
  File "export.py", line 750, in <module>
    _main()
  File "export.py", line 746, in _main
    e.run()
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\base.py", line 123, in run
    self.save_raw(self.effect())
  File "export.py", line 323, in effect
    self.processExportLayer()
  File "export.py", line 468, in processExportLayer
    kicad_edgecut_string = self.exportEdgeCut(kicad_mod = options.filetype == "kicad_module")
  File "export.py", line 659, in exportEdgeCut
    y = (path[1][1])
IndexError: list index out of range

The virus example file works well. Tried with another design I had and works well too. It means there is a problem with my design.
Could you explain how to draw the Edge.Cuts more in depth?

**Comment by GuillermoTell** [comment]
I don't know why, but if you enable all the layers when you prepare the document it works. I was using just Edge.Cuts, F.Cu and F.Mask-auto. Is there any mandatory layer?

**Comment by badgeek** [comment]
for now drill layer is mandatory, i will fix on weekend

**Comment by badgeek** [comment]
this is fixed in latest v 0.8.1.7 @GuillermoTell
