### ISSUE TITLE
Error when "prepare document"

### ISSUE THREAD

**Issue by ARKopp** [badgeek/svg2shenzhen#106]
I am getting this error when clicking on "prepare document". I am using windwos ... 

Traceback (most recent call last):
  File "prepare.py", line 322, in <module>
    _main()
  File "prepare.py", line 318, in _main
    e.run()q

**Comment by badgeek** [comment]
need your inkscape version and svg2shenzhen version

**Comment by ARKopp** [comment]
I installed inkscape 1.0 and now it works. I found the same issue already.  Before I had 0.92
