### ISSUE TITLE
No perfect horizontal and vertical lines

### ISSUE THREAD

**Issue by BitBlit88** [badgeek/svg2shenzhen#120]
I observed that some lines that were perfect horizontal or vertical in Inkscape aren't perfect horizontal or vertical after exporting them to Kicad.
I also noticed that it is depending on the positioning. While a line is not perfect horizontal or vertical, it will be if it's moved some mm in x or y position.
It looks like a rounding error.
I attached some screenshots, the source svg file and the generated Kicad mod.

![01_antenna](https://user-images.githubusercontent.com/53899482/108062756-896e3200-705a-11eb-93d9-3a30a9739ee3.png)
![02_antenna](https://user-images.githubusercontent.com/53899482/108062757-8a06c880-705a-11eb-818a-2d402984ec28.png)
[antenna.zip](https://github.com/badgeek/svg2shenzhen/files/5988523/antenna.zip)

**Comment by Sodium-Hydrogen** [comment]
This is an artifact from the lossy conversion that svg2shenzhen uses. See #107 
I am working on making [svg2mod](/svg2mod/svg2mod) a more complete tool then I'll be able to work on adding it as an optional parser. If you are comfortable with the command line svg2mod can work for your case until then

**Comment by BitBlit88** [comment]
thank you, svg2mod worked perfectly.
