### ISSUE TITLE
miss libxml2 [mac]

### ISSUE THREAD

**Issue by DaveCalaway** [badgeek/svg2shenzhen#29]
I try to install it by "brew install libxml2" but does not works anyway.

> The fantastic lxml wrapper for libxml2 is required by inkex.py and therefore this extension.Please download and install the latest version from http://cheeseshop.python.org/pypi/lxml/, or install it through your package manager by a command like: sudo apt-get install python-lxml
> 
> Technical details:
> No module named lxml

**Comment by kasbah** [comment]
Have you tried?

```
pip install lxml
```
