### ISSUE TITLE
inverting the soldemask layer

### ISSUE THREAD

**Issue by dusjagr** [badgeek/svg2shenzhen#3]
It would be great to have a tickbox to choose that the soldermask layer gets inverted. if its a simple hand-drawn style it ok to just duplicate the copper layer and put it in the soldermask, so all area outside of the copper gets masked without inversion.

but if i want to have a dedicated design with the soldermask, best to to be able to draw it as it is and do the inverting behind the scene during export to kicad.

**Comment by badgeek** [comment]
implemented this e297a0ace81b4ab6a0ddb822eeecbf558aca595f
