### ISSUE TITLE
prepare document now allows non square size

### ISSUE THREAD

**Issue by badgeek** [badgeek/svg2shenzhen#31]
hi @kasbah im pushing new update, this is a bug from the beginning and finally i managed to fix it, need to compile bitmap2component to all platform again (i hate it) i'll do it when i have more free time..

**Comment by badgeek** [comment]
- [x] osx build
- [x] windows build 
- [x] linux build

**Comment by kasbah** [comment]
I could try and do the linux build if that helps.

**Comment by badgeek** [comment]
that would help!, you will need 
https://github.com/badgeek/svg2shenzhen/files/2404261/boost.zip and extract it under include folder, so the path would be include/boot/*

and "sh build.sh" from the src folder.

**Comment by kasbah** [comment]
Does it matter whether the machine is 32-bit or 64-bit?

**Comment by badgeek** [comment]
i prefer 64 because common distro using 64 bit.. and i have 32 bit machine here so i can compile it myself

**Comment by badgeek** [comment]
tried to compile on my linux vps and gave me this

```
bitmap2component.o: In function `bitmap2component(potrace_bitmap_s*, _IO_FILE*, OUTPUT_FMT_ID, int, int, BMP2CMP_MOD_LAYER)':
bitmap2component.cpp:(.text+0xd1): undefined reference to `potrace_param_default()'
bitmap2component.cpp:(.text+0x12d): undefined reference to `potrace_trace(potrace_param_s const*, potrace_bitmap_s const*)'
bitmap2component.cpp:(.text+0x155): undefined reference to `potrace_state_free(potrace_state_s*)'
bitmap2component.cpp:(.text+0x161): undefined reference to `potrace_param_free(potrace_param_s*)'
bitmap2component.cpp:(.text+0x345): undefined reference to `potrace_state_free(potrace_state_s*)'
bitmap2component.cpp:(.text+0x351): undefined reference to `potrace_param_free(potrace_param_s*)'
```

i think i changed the build script for linux and my old vps is dead now...so i will need to figure out how to fix this..

**Comment by badgeek** [comment]
Found out the problem, we need to compile potrace first

i'll document compilation step here...

Prepare Boost

```
cd svg2shenzhen
cd include
wget https://github.com/badgeek/svg2shenzhen/files/2404261/boost.zip
unzip boost.zip
rm -fr boost.zip
```

Compile libpotrace

```
cd svg2shenzhen
cd potrace
rm -fr CMakeCache.txt
cmake .
make
```

Compile bitmap2component

```
cd svg2shenzhen
cd src
sh build.sh
chmod +x bitmap2component
mv bitmap2component bitmap2component_linux64
```
