### ISSUE TITLE
Checkbox to hide Val and Ref

### ISSUE THREAD

**Issue by 4b11b4** [badgeek/svg2shenzhen#35]
I was wondering if it might be possible to add a checkbox to set the Value and Reference text to "not visible" from the Step 2 Menu within Inkscape?

**Comment by kasbah** [comment]
You mean when you export the whole thing to a kicad module? I think we should just make it invisible by default.

**Comment by 4b11b4** [comment]
I would agree.
Most of the time you'll be making features which won't need the Val and Ref silkscreen fields?
A checkbox (checked by default) would give people the option though.

**Comment by kasbah** [comment]
I think we don't even need a checkbox because you can fairly easily override/change this in KiCad.

**Comment by 4b11b4** [comment]
True. It is probably the default case that people will not need a %V and %R, since this tool is primarily for making symbols and art.

**Comment by 4b11b4** [comment]
@badgeek What do you think? I will make a pull request.

**Comment by 4b11b4** [comment]
@badgeek Would you kindly confirm if this is the appropriate file to modify?

svg2shenzen/inkscape/svg2shenzen/**export.py**
_append after line 463_

**Comment by 4b11b4** [comment]
This would be appended after line 463:

(fp_text reference Ref** (at 0 0) (layer F.SilkS) hide
    (effects (font (size 1.27 1.27) (thickness 0.15)))
  )
  (fp_text value Val** (at 0 0) (layer F.SilkS) hide
    (effects (font (size 1.27 1.27) (thickness 0.15)))
  )

I just tested this in practice and it works.
(KiCad 6.0.0-rc1)

I do not believe the .kicad_mod files have changed from 5 to 6 or plan to in the future, but it could be tested on 5.0 first.

**Comment by 4b11b4** [comment]
#37

**Comment by badgeek** [comment]
i'll test it
