### ISSUE TITLE
Can't deal with this spiral as edge cuts

### ISSUE THREAD

**Issue by kasbah** [badgeek/svg2shenzhen#39]
Just working on the FOSDEM tutorial and noticed that this spiral doesn't work. :snail: 

![image](https://user-images.githubusercontent.com/206854/51947527-1f57a580-241d-11e9-8ddf-60823640b6d1.png)
![image](https://user-images.githubusercontent.com/206854/51947533-254d8680-241d-11e9-8ddd-f7f47cbd348a.png)

[example.tar.gz](https://github.com/badgeek/svg2shenzhen/files/2810143/example.tar.gz)

**Comment by kasbah** [comment]
Looks like the problem was the paths weren't joined up on the inner tip of the spiral. Joining paths there fixes it. 

![image](https://user-images.githubusercontent.com/206854/51947940-875abb80-241e-11e9-8a45-43424998a18d.png)

**Comment by badgeek** [comment]
i remember i tried this crazy spiral, almost fired up inkscape and test it again 😆
