### ISSUE TITLE
rounded corners on boxes

### ISSUE THREAD

**Issue by 5shekel** [badgeek/svg2shenzhen#4]
might be the small size of the sketch?  
all objects are converted to a path.  
but i get rounded corners where there shouldn't be  

![pic](https://i.imgur.com/Z0EEoJV.png)

[svg srouce](https://github.com/shenkarSElab/TinyTony/blob/master/board/TinyTony_ShenzenReady_board.svg)

**Comment by badgeek** [comment]
image is too small, fix set export dpi to 2000 but the extension that you have now max dpi is 1000... will add the fix on next release

![screenshot_128](https://user-images.githubusercontent.com/64752/38165165-61755760-3539-11e8-98e5-1b566e27f086.png)

**Comment by 5shekel** [comment]
my setup limits me to 1000dpi, even if i set it on 2000.
after i updated to your fix

**Comment by badgeek** [comment]
aha i forgot to update readme, its now pointing to release section

**Comment by 5shekel** [comment]
works!

**Comment by badgeek** [comment]
bitmap2component will still import using 600 dpi as scale, fixed in version 0.2.3
