### ISSUE TITLE
 Does it work on Kicad 5? 

### ISSUE THREAD

**Issue by marsfactory** [badgeek/svg2shenzhen#42]
![sin titulo](https://user-images.githubusercontent.com/32801212/52757444-6af47c80-2fe3-11e9-8099-545bba76d3d7.jpg)

**Comment by marsfactory** [comment]
![sin titulo2](https://user-images.githubusercontent.com/32801212/52757551-cde61380-2fe3-11e9-9853-0da02d5c7784.jpg)

Fmask and Edge cuts go up, but I can not get Fcup up

**Comment by badgeek** [comment]
@marsfactory is it solved? should be works with kicad 5 cc @kasbah

**Comment by marsfactory** [comment]
Sorry buddy, the problem is solved. Lack of sleep is the problem. The copper layer was not black, so Kicad did not charge it. Thank you!!!
