### ISSUE TITLE
Prepare document gives lxml dependency error (Windows).

### ISSUE THREAD

**Issue by ninjatill** [badgeek/svg2shenzhen#45]
Hello,

I am using Windows 7 with Inkscape 0.92.4 and svg2shenzhen 0.2.16. When running prepare document, I'm getting an error that the "...lmxml wrapper for libxml2 is required...". I ran an administrator command prompt and ran "pip install lxml". The install finishes successfully. I close Inkscape and reopen and run prepare document again... I get the same dependency error. If I go back to the windows command prompt and run the "pip install lxml" command again, it says that the "requirement already satisfied". So then the question is how to get around this dependency error?

The other issues similar do not seem to have a specific resolution for this dependency error after the dependency is installed via pip. Thanks,

**Comment by ninjatill** [comment]
Prepare docs dependency error:
![image](https://user-images.githubusercontent.com/15878493/57861515-be35c100-77c4-11e9-8618-a705c5cca8a6.png)


After installing lxml via pip, if I run "pip install lxml" again, I get this message that the package is already installed:
![image](https://user-images.githubusercontent.com/15878493/57861350-6e56fa00-77c4-11e9-8c68-9086871be78c.png)

**Comment by kasbah** [comment]
It's likely that pip and inkscape are using different versions of python. I believe the plugin only works with python2 and I can see in your screenshot pip is working with python 3.6 (`python_36_64`). Unfortunately I don't use Windows very much so don't know how to resolve it.

**Comment by ninjatill** [comment]
OK. That makes sense. I'll see if I can resolve that. I have multiple software products on the PC that require different versions.
