### ISSUE TITLE
Not creating files in Windows

### ISSUE THREAD

**Issue by twinkletwinkie** [badgeek/svg2shenzhen#5]
Attempting to run the Export command gives errors:

`"C:\Users\username\AppData\Roaming\inkscape\extensions\bitmap2component.exe" "C:\Users\username\test\images\001_F.Cu.png" "C:\Users\username\test\pcbart.pretty\001_F.Cu.kicad_mod" F.Cu true 600 128
"C:\Users\username\AppData\Roaming\inkscape\extensions\bitmap2component.exe" "C:\Users\username\test\images\002_F.Mask.png" "C:\Users\username\test\pcbart.pretty\002_F.Mask.kicad_mod" F.Mask true 600 128
"C:\Users\username\AppData\Roaming\inkscape\extensions\bitmap2component.exe" "C:\Users\username\test\images\003_F.Silk.png" "C:\Users\username\test\pcbart.pretty\003_F.Silk.kicad_mod" F.Silk true 600 128
Traceback (most recent call last):
  File "export_layers.py", line 671, in <module>
    _main()
  File "export_layers.py", line 667, in _main
    e.affect()
  File "C:\Program Files\Inkscape\share\extensions/inkex.py", line 283, in affect
    self.effect()
  File "export_layers.py", line 311, in effect
    self.processExportLayer()
  File "export_layers.py", line 382, in processExportLayer
    with open(kicad_file, 'r') as myfile:
IOError: [Errno 2] No such file or directory: 'C:\\Users\\username\\test\\pcbart.pretty\\001_F.Cu.kicad_mod'
`

Even if I manually create the directory it's looking for it won't create the files.  It appears to work fine when done in Ubuntu.

**Comment by badgeek** [comment]
could you upload what is in test folder?

**Comment by twinkletwinkie** [comment]
Folders:
Pcbart.pretty
Images

Images has .png files.

**Comment by badgeek** [comment]
From command prompt, paste this 
C:\Users\username\AppData\Roaming\inkscape\extensions\bitmap2component.exe

And press enter, what is the ouput?

**Comment by twinkletwinkie** [comment]
![85fbe16e-e7ad-429d-aa1d-013aeea370b2](https://user-images.githubusercontent.com/5308062/38468156-2ecd17ee-3b10-11e8-97c0-337bc16dff24.jpeg)

**Comment by badgeek** [comment]
extract and open bitmap2component, and what is the output?

[bitmap2component.exe.zip](https://github.com/badgeek/svg2shenzhen-next/files/1888060/bitmap2component.exe.zip)

**Comment by twinkletwinkie** [comment]
![image](https://user-images.githubusercontent.com/5308062/38474700-da0c9594-3b6f-11e8-8bb7-763b77f6554e.png)

**Comment by badgeek** [comment]
no bitmap2component.exe ?

**Comment by badgeek** [comment]
just run the exe./..

**Comment by twinkletwinkie** [comment]
I misunderstood what you were asking me. I didn't realize that you had linked to an updated version of bitmap2component.exe, it wasn't obvious from the email I received.  

It appears to be working correctly now, thank you very much.

**Comment by twinkletwinkie** [comment]
I processed the example you provided and it says "LOGO***" in the middle of the board.  Is it supposed to do that?

![image](https://user-images.githubusercontent.com/5308062/38475341-88f687a4-3b75-11e8-8686-a132a102b524.png)

**Comment by badgeek** [comment]
yes that is correct, i will push new release with this fix
