### ISSUE TITLE
Fix file permission on Linux and directly install using git

### ISSUE THREAD

**Issue by alexpacini** [badgeek/svg2shenzhen#52]
Similarly to #2 , the latest version is still not working because of a missing executable bit
`chmod +x ~/.config/inkscape/extensions/bitmap2component_linux64`

```python
Traceback (most recent call last):
  File "export.py", line 752, in <module>
    _main()
  File "export.py", line 748, in _main
    e.affect()
  File "/usr/share/inkscape/extensions/inkex.py", line 283, in affect
    self.effect()
  File "export.py", line 324, in effect
    self.processExportLayer()
  File "export.py", line 490, in processExportLayer
    with open(kicad_file, 'r') as f:
IOError: [Errno 2] No such file or directory: '/tmp/.svg2shenzhen-cache/customshapekicad.pretty/F.Cu_g824.kicad_mod'
```

I think it is because of the zip archive. A tar.gz should maintain the proper permissions.
Can you add this to the install instructions?

On a side note, is it possible to install this plugin using directly the git repo?
All my freecad and kicad plugins are installed in this way and I wonder if I can do the same using svg2shenzen and inkscape.

Thanks for the amazing tool!

**Comment by Moonbase59** [comment]
Same here, almost wanted to give up. The …_osx has the executable bit, albeit the …_linux64 hasn’t.
