### ISSUE TITLE
Only the "Edge.Cut" and "Drill" Layers are being exported to Kicad

### ISSUE THREAD

**Issue by LycheeYum** [badgeek/svg2shenzhen#60]
Windows 10 
Inkscape 0.92.4 
KiCad 5.1.5 

As the title states I'm only able to get the Edge.Cut and Drill layers to export to KiCad.  

I've tried with multiple inskcape files, even the sample viruspcb.svg located in the repository, all the the same results.

**Comment by Jegeva** [comment]
read the doc :) (ie. remove -disabled from the layer name)
