### ISSUE TITLE
Different solder mask clearance?

### ISSUE THREAD

**Issue by Moonbase59** [badgeek/svg2shenzhen#63]
I need to produce a "shine-through" PCB (text with LEDs behind). I can put an exact duplicate of my text on the F.Cu and F.Mask layers but the letters on the Mask will always be "bigger" (i.e. some solder mask clearance is auto-added). Changing the solder mask clearance in PCBnew afterwards doesn’t help.

The PCB looks really awful with the copper layer "bleeding" into the letters …

Is there any trick or workaround to get a zero solder mask clearance?

**Comment by arduino12** [comment]
Hi,

I think this is our problem (taken from the generated kicad file):
![image](https://user-images.githubusercontent.com/11454280/78391341-db4acc80-75ee-11ea-85c7-3ada2720cfaa.png)

**`svg2shenzhen` needs to set the `solder mask clearance` to 0 before adding the layers...**

How can we fix it in the code? (setting it after the script doesn't work..)

Thanks,
Arad

**Comment by rcludwick** [comment]
Also having played around with that, it's looks like on kicad 5.1.5 the solder mask isn't rendered correctly until you generate the gerbers.  So the 3d viewer doesn't respect it apparently.
