### ISSUE TITLE
Unclear in the documentation, please update

### ISSUE THREAD

**Issue by Jegeva** [badgeek/svg2shenzhen#66]
The extention contains a CLI version for the png2composant executable. If it is not chmod+x'ed underlinux, any layer that is enabled and relying on a component creation will make the export crash due to the .kicad_mod not existing.

chmod +x 'ing the executable solves the problem but it should be clear in the install doc.

**Comment by kasbah** [comment]
Thanks for reporting but it's a duplicate of #2 (oh, it's closed :thinking: ?) and #52
