### ISSUE TITLE
SVGSZ_VER Instead of 0.2.17

### ISSUE THREAD

**Issue by twinkletwinkie** [badgeek/svg2shenzhen#71]
OS: Windows 10
Inkscape Ver: 0.92.4

When svg2shenzhen is installed instead of display "0.2.17" it shows "SVGSZ_VER" where the version number should be displayed.

**Comment by joanbono** [comment]
Same error on macOS 10.15.4 with Inkscape 1 beta and Debian 10 with Inkscape 0.92.4

**Comment by rcludwick** [comment]
Also with ubuntu using the latest inkscape snap.

**Comment by grantbreaksthings** [comment]
Same error on Debian Buster, Inkscape 0.92

**Comment by iharshadec** [comment]
Same text I see on Win 10 + Inkscape 1.0 version.

**Comment by badgeek** [comment]
fixed in latest build v.18
