### ISSUE TITLE
svg:use elements are not supported

### ISSUE THREAD

**Issue by smiler** [badgeek/svg2shenzhen#73]
I use a lot of clone objects through the `<svg:use>` element in my designs. Currently these seem to be ignored by the exporter.

**Comment by badgeek** [comment]
it should not be, check out where is your clone layer at?

**Comment by smiler** [comment]
I don't have the file I had issues with left, I ended up redoing the design without clone objects so unfortunately I can't give you a repro. Should've attached the file when I reported the bug, sorry :(

**Comment by badgeek** [comment]
np @smiler sorry for late repond
