### ISSUE TITLE
silkscreen is exported as copper 

### ISSUE THREAD

**Issue by x70b1** [badgeek/svg2shenzhen#80]
I found out that `svg2shenzhen` translates the silkscreen layer to a copper layer. But thats obviously wrong.
To fix this I can manually edit the layer in the exported `.kicad_pcb` file. That would work.

Maybe it was my mistake. I tried a lot of things. But I always came to the same conclusion.

The `svg2shenzhen` was build from the latest commit on master branch. 
Inkscape is 1.0 (4035a4fb49, 2020-05-01).

The example:
![inkscape](https://user-images.githubusercontent.com/10016267/88384052-ff076d80-cdab-11ea-883a-3e8197be8acb.png)
![kicad](https://user-images.githubusercontent.com/10016267/88384055-00389a80-cdac-11ea-875d-04a5b442752f.png)

**Comment by jollydodo** [comment]
Same problem here. Any idea what could be causing this issue? (Using MacOS 10.15.6 and the latest commit)

**Comment by fstokke** [comment]
I think this is a problem with the latest builds of bitmap2component.exe, see issue #75. On Windows I tried reverting to the previous version and that one worked OK.

**Comment by x70b1** [comment]
@fstokke do you know what is required to fix this?

**Comment by fstokke** [comment]
I see @amcewen has fixed the problem on Linux by recompiling bitmap2component from source (see issue #75), so maybe a recompile will fix the problem on Mac as well. Unfortunately I don't have the build environment for compiling from source.

**Comment by x70b1** [comment]
I am on linux and I used `make` to rebuild bitmap2component binary. 
This seems to fix the issues.

We should update the binaries and close all the copper/silkscreen issues.

**Comment by badgeek** [comment]
@x70b1 @fstokke this will be fixed in v.18 with your PR @fstokke thank you, with new build system using travis i hope its easier to update
