### ISSUE TITLE
Extension menu items (prepare document & export to kicad) are disabled

### ISSUE THREAD

**Issue by herpiko** [badgeek/svg2shenzhen#89]
I'm using the latest version (0.2.18.5). However the About menu is not disabled and can be clicked, showing the about dialog as expected. I've tried to downgrade the version but it didn't work either.

### Ubuntu 18.04 with Inkscape 1.0 (1.0+r73+1) from PPA (ppa:inkscape.dev/stable)
![svg2shenzhen-ubuntu](https://user-images.githubusercontent.com/2534060/90684873-19d9de80-e293-11ea-844c-830ae5bb56c3.jpg)

### macOS Mojave with Inksape 1.1-dev (48d18c81, 2020-07-08)
<img width="1071" alt="Screen Shot 2020-08-20 at 03 06 18" src="https://user-images.githubusercontent.com/2534060/90684974-4130ab80-e293-11ea-9d78-8e49d12b0a12.png">

**Comment by badgeek** [comment]
@herpiko Hi, we havent test the extension with inkscape 1.1-dev yet, please try with inkscape 1.0 instead, why would you use dev version of inkscape?

**Comment by badgeek** [comment]
please use svg2sz latest v0.2.18.6 https://github.com/badgeek/svg2shenzhen/releases/tag/0.2.18.6

**Comment by herpiko** [comment]
@badgeek Thanks for your fast response.

Ok, I'll try it with 0.2.18.6.

**Comment by aa956** [comment]
0.2.18.6 just behaved the same way on Windows when installed into svg2shenzhen subdirectory of Inkscape user extensions directory:

So menu items disabled if extension unpacked to:
%APPDATA%/inkscape/extensions/svg2shenzhen/

menu items enabled if extension unpacked directly to:
%APPDATA%/inkscape/extensions/

**Comment by badgeek** [comment]
@aa956 what is your inkscape version?

**Comment by aa956** [comment]
Inkscape version: 1.0 (4035a4fb49, 2020-05-01)

**Comment by badgeek** [comment]
directory layout should be like this :
![screenshot_1728](https://user-images.githubusercontent.com/64752/90862698-04aaa000-e3b8-11ea-86e8-bbd45e4ae6a8.png)

i think i need a better install instructions

**Comment by aa956** [comment]
Another option is to change inx file from:
```
    <script>
        <command reldir="extensions" interpreter="python">svg2shenzhen/export.py</command>
    </script>
```
to
```
    <script>
        <command location="inx" interpreter="python">svg2shenzhen/export.py</command>
    </script>
```
as recommended here: [Updating your Extension for 1.0
](https://wiki.inkscape.org/wiki/index.php/Updating_your_Extension_for_1.0)

If I understand correctly this change will enable installation anywhere under extensions directory?

**Comment by badgeek** [comment]
@aa956 thanks for pointing this out, will try later
