### ISSUE TITLE
Prepare document throw error

### ISSUE THREAD

**Issue by badgeek** [badgeek/svg2shenzhen#90]
![screenshot_1724](https://user-images.githubusercontent.com/64752/90709057-8968c180-e2c5-11ea-96de-96219b4a23dd.png)

**Comment by badgeek** [comment]
@twinkletwinkie  kicadLayers.items returns dict_keys which need to be wrapped with list(... )

**Comment by badgeek** [comment]
https://github.com/badgeek/svg2shenzhen/blob/0dc743cd4518bfae795154d72c53b5ebeff8f7e2/inkscape/svg2shenzhen/prepare.py#L172

**Comment by badgeek** [comment]
- Fixed in https://github.com/badgeek/svg2shenzhen/releases/tag/0.2.18.6

**Comment by twinkletwinkie** [comment]
Strange. I don’t understand why that would throw an error now when it doesn’t on my computers.

**Comment by badgeek** [comment]
what is your OS/inkscape version? @twinkletwinkie

**Comment by badgeek** [comment]
this is the tricky part with python inside inkscape, that is why i have big mess of ifs to keep the code minimal, i hope this will not break again

**Comment by twinkletwinkie** [comment]
Windows 10 1909 and Inkscape 1.0

**Comment by badgeek** [comment]
For note: broken on Inkscape 1.0 (4035a4f, 2020-05-01) OSX 10.13.6 (17G11023) High Sierra
