### ISSUE TITLE
0.2.18 svg2shenzhen greyed out

### ISSUE THREAD

**Issue by Xcreed** [badgeek/svg2shenzhen#91]
Just installed Inkscape 1.0 on Windows 10, followed the instructions from the Readme.md and when I click on the extension, only "About" is not greyed out. Reinstalled Inkscape, reinstalled Python, tried with the viruspcb example, no luck. Any ideas?

**Comment by iharshadec** [comment]
Follow this steps. Download :- https://github.com/badgeek/svg2shenzhen/releases/download/0.2.18.6/svg2shenzhen-extension-0.2.18.6.zip

Extract it and it will be like this.
![image](https://user-images.githubusercontent.com/20681096/90946430-526fe880-e44a-11ea-869d-bb28428c0e24.png)

Copy this all and 

**Option 1**
Go to **C:\Users\"YourUser"\AppData\Roaming\inkscape\extensions**

**Option 2**
you can also do **"win+R"** and type **%appdata%** then go to **inkscape\extensions**

**Option 3**
Open Inkscape and go **Edit-->Preferences**
![image](https://user-images.githubusercontent.com/20681096/90946528-518b8680-e44b-11ea-9626-683f8e77a90f.png)

Then Go to System and you will see Option User extensions: you can hit Open and it will open up folder directly.
![image](https://user-images.githubusercontent.com/20681096/90946588-e0989e80-e44b-11ea-9e66-100d0320edca.png)
![image](https://user-images.githubusercontent.com/20681096/90946591-eaba9d00-e44b-11ea-9665-799b850c7606.png)


### **And paste those all there and restart Inkscape** 

![image](https://user-images.githubusercontent.com/20681096/90946463-9cf16500-e44a-11ea-95f3-a6f2e344f7dd.png)

**Comment by badgeek** [comment]
thanks @iharshadec

**Comment by iharshadec** [comment]
> thanks @iharshadec

I am not sure how to do Pull Request and then submit Merge but I was thinking I can do update README.md with this kind of screenshot ways for installing.

**Comment by Xcreed** [comment]
Awesome, just followed them and it worked perfectly. Thanks!
